### ISSUE TITLE
theme not loading 

### ISSUE THREAD

**Issue by rpkaul** [ZPE-Online/Theme-MasterControlProgram#2]
that's weird but its not working for me , I am getting plain HTML CSS page while selecting the MCP theme. i am following all the steps downloaded the theme and uploaded on website .

[
![image](https://user-images.githubusercontent.com/21355500/121797558-91bc2f80-cc3e-11eb-81e8-66d105eb77df.png)
](url)

**Comment by P34NUT85** [comment]
Hello rpkaul, 

There will be an issue on your side of the installation somewhere, please make sure to check the directory for the following

var => www => html =>themes => MasterControlProgram 

 MasterControlProgram is named "MasterControlProgram"
 
 You may need to rename the folder in the Themes folder from Theme-MasterControlProgram-main to MasterControlProgram.
 
 Please let us know if this resolves the issue for you, and we will note this in the installation steps for future downloads. We are there is no issue with the theme itself, as only the CSS has been changed so far from the ondesen SimpleBootstrap theme
 which you can find here: https://github.com/OpenGamePanel/Theme-SimpleBootstrap

**Comment by y4ahmad** [comment]
Hello rpkaul,

The issue can be with file path as I can see in, its not loading CSS files. So you just have to check the file path and theme folder name should be like this.

![image](https://user-images.githubusercontent.com/25535112/122946154-c0e94400-d396-11eb-80be-01957895a9a0.png)

Also please check with file permissions, why the CSS is not loading. If you still have any concern then share your website URL where you have uploaded the theme.

**Comment by rpkaul** [comment]
@y4ahmad @P34NUT85 hey guys thank you so much its working fine now after the folder rename .
it was `Master Control Program`  before
